# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed Jul  9 00:45:50 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Pictor(object):
    def setupUi(self, Pictor):
        Pictor.setObjectName("Pictor")
        Pictor.resize(883, 531)
        self.centralwidget = QtGui.QWidget(Pictor)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.browser = QtGui.QWidget(self.centralwidget)
        self.browser.setMaximumSize(QtCore.QSize(300, 16777215))
        self.browser.setObjectName("browser")
        self.verticalLayout = QtGui.QVBoxLayout(self.browser)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtGui.QWidget(self.browser)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_picture = QtGui.QPushButton(self.widget_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("statics/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_picture.setIcon(icon)
        self.add_picture.setObjectName("add_picture")
        self.horizontalLayout_2.addWidget(self.add_picture)
        self.add_folder = QtGui.QPushButton(self.widget_3)
        self.add_folder.setIcon(icon)
        self.add_folder.setObjectName("add_folder")
        self.horizontalLayout_2.addWidget(self.add_folder)
        self.verticalLayout.addWidget(self.widget_3)
        self.treeView = QtGui.QTreeView(self.browser)
        self.treeView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeView.setIconSize(QtCore.QSize(70, 70))
        self.treeView.setAnimated(True)
        self.treeView.setWordWrap(True)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(False)
        self.verticalLayout.addWidget(self.treeView)
        self.horizontalLayout.addWidget(self.browser)
        self.images = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.images.sizePolicy().hasHeightForWidth())
        self.images.setSizePolicy(sizePolicy)
        self.images.setMinimumSize(QtCore.QSize(400, 0))
        self.images.setObjectName("images")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.images)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addWidget(self.images)
        self.widget_4 = QtGui.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_5 = QtGui.QPushButton(self.widget_4)
        self.pushButton_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("statics/icons/facebook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.widget_4)
        self.pushButton_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_6.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("statics/icons/twitter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon2)
        self.pushButton_6.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtGui.QPushButton(self.widget_4)
        self.pushButton_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_7.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("statics/icons/pinterest.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon3)
        self.pushButton_7.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_10 = QtGui.QPushButton(self.widget_4)
        self.pushButton_10.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_10.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("statics/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_8 = QtGui.QPushButton(self.widget_4)
        self.pushButton_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_8.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("statics/icons/flickr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon5)
        self.pushButton_8.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_3.addWidget(self.pushButton_8)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget_4)
        Pictor.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Pictor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 883, 25))
        self.menubar.setObjectName("menubar")
        Pictor.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Pictor)
        self.statusbar.setObjectName("statusbar")
        Pictor.setStatusBar(self.statusbar)

        self.retranslateUi(Pictor)
        QtCore.QMetaObject.connectSlotsByName(Pictor)

    def retranslateUi(self, Pictor):
        Pictor.setWindowTitle(QtGui.QApplication.translate("Pictor", "Pictor", None, QtGui.QApplication.UnicodeUTF8))
        self.add_picture.setText(QtGui.QApplication.translate("Pictor", "Picture", None, QtGui.QApplication.UnicodeUTF8))
        self.add_folder.setText(QtGui.QApplication.translate("Pictor", "Folder", None, QtGui.QApplication.UnicodeUTF8))

